version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finanzas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Insomnio14.
      POSTGRES_DB: db_finanzas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: